### ISSUE TITLE
Updating fields to null

### ISSUE THREAD

**Issue by Vulcannis** [kstateome/canvas-api#67]
I don't see any other issues in the repo, so let me know if there's another preferred place to discuss things.

We at UBC have a need to edit sections, including clearing the `start_at` and `end_at` properties. With the Canvas REST JSON API this is done by setting them to null. Unfortunately this conflicts with the default behaviour of GSON, which is to not serialize null fields, and GSON only let's you toggle this per `GsonBuilder` instance. So no field-level control.

Fortunately (for this case) a new builder is created for each request, so it would be possible to add some extra control in the API to affect it.  For example:

1. Make this a class-level option. Add a new field to the `CanvasObject` annotation (or a whole new annotation), say `includeNullValues`, defaulting to false and use that when building the `GsonBuilder` instance. This would satisfy our use case, as we initialize the Section model instance with all existing values before applying changes and thus won't lose any data. However any existing clients that are relying on the current behaviour could start losing data.
1. New setters could be created for those fields (`setStartAtToNull`? `clearStartAt`?) and the new null behaviour only triggered if they are called. This is obviously safer but not as clean design-wise.
1. Switch to a different JSON library, like Jackson, which let's you scope null handling on a per-field basis. Would still have to do something like 1 and 2, but could limit the nulls to only fields that actually matter.
1. More complicated designs using `Optional` or better yet a new monad tailored for this case. This would be a lot of work for dubious gain, however.

What does everyone think? Any better ideas?

Of course the root issue is that the model classes are used for both representing values and changes to values, but solving that properly is not trivial with Java.

**Comment by killsto** [comment]
I think the Monad idea might be the best solution even though it sounds like overkill. I will have to spend time to look at the problem more closely.

> Of course the root issue is that the model classes are used for both representing values and changes to values, but solving that properly is not trivial with Java.

Could you expand on this a bit? I'm confused by the wording. Do you mean that instead of updating the model one could use a new type for each change which is more commonly done in other languages?

**Comment by ToeBee** [comment]
This is definitely an interesting problem. We do a lot more read operations from Canvas than write operations so we haven't hit some of these edge cases yet in our own code. I know I have spotted some native int or long types being used that we had to change to Object Integer/Long types because they were being automatically initialized to zero and then serialized out to JSON. This ended up changing values in Canvas that we were not intending on touching.

However it might not be out of the question to use approach 1 and possibly even change the default behavior of Gson. While this is not enforced by the API, generally you will only be PUT/POSTing objects that you have recently queried from Canvas. (with the obvious exception of calls that are creating a new object in Canvas) So all the fields should in theory have the values (or lack of value) that match what is in Canvas and writing them all back should not cause any changes except for what you have explicitly changed in your code since querying the object from Canvas. The one place I could see this breaking horribly is if you query an object form Canvas as a user who does not have roles/permissions to see some restricted fields but then write back as a different user who has more permissions. I would call this extremely bad practice but come to think of it, we may actually be doing this in one of our LTI applications due to some caching we do...

**Comment by Vulcannis** [comment]
@killsto

I meant that changes to model instances is most accurately implemented as a set of property changes (to a particular key/id), but it's usually done by just re-using the model classes themselves and leaning on nulls as special values. Both the Java API and the Canvas REST API do this, though the latter can get away with it because of JSON's null/undefined distinction. With Java we can't do both null and undefined without introducing something.

I think the monad approach is definitely overkill and would be cumbersome in this case, even though it appeals to the purist in me. If we could apply a monad to a java type, e.g. Optional(Section) -> a Section class with all fields Optional, then we could more easily leverage the existing model classes. I'm sure Haskell has ways of doing this, and I think the Typescript type system might be able to as well. With Java though we'd be stuck essentially duplicating the model classes or losing static type checking by leveraging reflection.

@toebee

We'd certainly prefer changing the global default (so I guess that'll be option 0) as it is the cleanest and easiest to implement, but then it doesn't break anything on our side. :)

> While this is not enforced by the API, generally you will only be PUT/POSTing objects that you have recently queried from Canvas

We're actually fetching the value again right before writing it back to minimize unintended edits. Fortunately our user volume for this is low enough that we don't need to worry about caching or anything. Caching & security are hard enough on their own, never mind combined.

How should we proceed? I can certainly submit commits for options 0 & 1 easily enough.

**Comment by killsto** [comment]
@Vulcannis: Sorry for the late reply. We did not add a card for this issue to our Kanban board and we forgot about it. I added a card and we will get back to you early this sprint (which starts tomorrow).

**Comment by ToeBee** [comment]
A couple of us discussed this today. We came up with one possible solution that preserves backward compatibility and didn't take too much work to implement. This was to make it an optional flag when requesting a writer object from the ApiFactory class. Kind of like how the pagination size can be specified when requesting a reader.

Please take a look at PR #72 and see what you think. I did not do a lot of testing but I did verify that I could blank out the end date of a section.

I don't like the fact that it adds even more to the already long list of constructor arguments in all of the implementation classes. But at least end users of the library are never exposed to that.

It also forces readers to pass the flag into the `getDefaultGsonParser` method even though they are not impacted by this.

The last thing I realized while writing this is that while this does fix the calls where we are using JSON, it does not affect some API calls where we are using a multipart form payload instead of JSON. For example the `editAssignmentGroup` and `enrollUser` methods.

We should probably try to move all of the calls towards using JSON. When we first started developing our LTI applications, one of our student developers thought there were some calls that didn't work with JSON and some that didn't work with a form payload. However I don't think anyone else actually double checked this claim. I suspect it may have just been some misunderstandings about how one or the other kind of payload is analyzed on the Canvas side. Either that or it is a legit bug in Canvas that we should push to get fixed because their documentation does state that calls should work either way.

**Comment by Vulcannis** [comment]
Makes sense. I hadn't done anything with setting custom pagination sizes so I didn't realize there was a convenient customization point. Should be fine for our purposes, and I'll give it a test as soon as I can.

**Comment by ToeBee** [comment]
@Vulcannis Have you had a chance to try this yet?

**Comment by Vulcannis** [comment]
Sorry, been a bit busy. Just tried it and it worked nicely, thanks!

**Comment by ToeBee** [comment]
Well this was merged and released in 1.0.16. It does need to be used carefully though. While working on some new course privacy/permission settings I noticed that the API does not return a lot of these new settings by default unless you specifically ask for them via `include[]=` parameters which are not documented. Using this new null serialization feature could unintentionally blank those values out.

We may need to move towards keeping track of the dirty state of every field in the model classes and only serialize those that are dirty when writing things to Canvas. But for now I am going to consider this issue closed.
